### PR TITLE
Trans main

### PR DESCRIPTION
**Pull request by binmurv**
Wala namang siyang conflict kaya ok lang na imerge. @carlomandam accept mo lang yung pull request.

### CODE REVIEW

**Comment by binmurv** [comment]
Wala naman siyang conflict kaya ok lang na imerge mo na. @carlomandam

**Comment by angeloPereyra** [comment]
lugi may import :grin:

**Comment by johnalfredclave** [comment]
Grabe talaga ung group neto malupit

**Comment by angeloPereyra** [comment]
group mo yan eh hahahahaha

**Pull request merged**
